---
jobs:
  - job: 'Linux'
    dependsOn: []
    strategy:
      matrix:
        Clang:
          compiler: clang
        GCC:
          compiler: gcc
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/steps/dependencies-python.yml
      - template: .azure-pipelines/steps/dependencies-linux.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          compiler: $(compiler)
          options: -Denable-wayland=false
          wrapper: valgrind --leak-check=full --track-origins=yes --error-exitcode=99

  - job: 'macOS'
    dependsOn: []
    pool:
      vmImage: 'macos-10.13'
    steps:
      - template: .azure-pipelines/steps/dependencies-python.yml
      - template: .azure-pipelines/steps/dependencies-macos.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          options: -Denable-wayland=false -Denable-x11=false
          prepare: 'export PATH="/usr/local/opt/bison/bin:${PATH}"'

  - job: 'Windows'
    dependsOn: []
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .azure-pipelines/steps/dependencies-python.yml
      - template: .azure-pipelines/steps/dependencies-windows.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          compiler: cl
          options: -Denable-wayland=false -Denable-x11=false -Denable-docs=false
          prepare: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64'
